CREATE TABLE `leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`idempotency_key` text NOT NULL,
	`lead_type` text NOT NULL,
	`applicant_role` text DEFAULT '' NOT NULL,
	`full_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text NOT NULL,
	`country` text NOT NULL,
	`player_age` integer,
	`preferred_route` text DEFAULT '' NOT NULL,
	`position` text DEFAULT '' NOT NULL,
	`current_club` text DEFAULT '' NOT NULL,
	`playing_level` text DEFAULT '' NOT NULL,
	`highlight_url` text DEFAULT '' NOT NULL,
	`education_level` text DEFAULT '' NOT NULL,
	`intended_study` text DEFAULT '' NOT NULL,
	`preferred_intake` text DEFAULT '' NOT NULL,
	`goal` text DEFAULT '' NOT NULL,
	`organization` text DEFAULT '' NOT NULL,
	`partner_interest` text DEFAULT '' NOT NULL,
	`message` text DEFAULT '' NOT NULL,
	`contact_preference` text DEFAULT '' NOT NULL,
	`consent` integer DEFAULT false NOT NULL,
	`source_url` text DEFAULT '' NOT NULL,
	`referrer` text DEFAULT '' NOT NULL,
	`utm_source` text DEFAULT '' NOT NULL,
	`utm_medium` text DEFAULT '' NOT NULL,
	`utm_campaign` text DEFAULT '' NOT NULL,
	`utm_content` text DEFAULT '' NOT NULL,
	`utm_term` text DEFAULT '' NOT NULL,
	`gclid` text DEFAULT '' NOT NULL,
	`fbclid` text DEFAULT '' NOT NULL,
	`language` text DEFAULT 'en' NOT NULL,
	`timezone` text DEFAULT '' NOT NULL,
	`form_variant` text DEFAULT '' NOT NULL,
	`crm_status` text DEFAULT 'queued' NOT NULL,
	`crm_response` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `leads_idempotency_key_unique` ON `leads` (`idempotency_key`);