export type FixtureLocation = "home" | "away";

export type PhoenixFixture = Readonly<{
  matchCode: number;
  week: number;
  round: 1 | 2;
  date: `${number}-${number}-${number}`;
  time: `${number}:${number}`;
  opponent: string;
  location: FixtureLocation;
  venue: string;
  streamUrl?: string;
}>;

export type FixtureTeamIdentity = Readonly<{
  name: string;
  crest?: string;
}>;

export const phoenixFixtureTeam: FixtureTeamIdentity = {
  name: "Phoenix United FC",
  crest: "/brand/phoenix-crest.svg",
};

export const fixtureOpponentTeams: Readonly<
  Record<string, FixtureTeamIdentity>
> = {
  PASS: { name: "PASS", crest: "/opponents/pass.png" },
  "Red Castle": { name: "Red Castle", crest: "/opponents/red-castle.png" },
  Stallions: { name: "Stallions", crest: "/opponents/stallions.png" },
  "Stryx FC": { name: "Stryx FC", crest: "/opponents/stryx-fc.png" },
  ISE: { name: "ISE", crest: "/opponents/ise.png" },
  Maracuja: { name: "Maracuja", crest: "/opponents/maracuja.png" },
  "Desert Falcon": { name: "Desert Falcons", crest: "/opponents/desert-falcon.png" },
  IRISH: { name: "Dubai Irish", crest: "/opponents/dubai-irish.png" },
  "Circle Football": { name: "Circle Football", crest: "/opponents/circle-football.png" },
  "Al Fath FC": { name: "Al Fath FC", crest: "/opponents/al-fath.png" },
  "Al Madinah Wanderers": { name: "Al Madinah Wanderers", crest: "/opponents/al-madinah-wanderers.png" },
  Olympic: { name: "Olympic", crest: "/opponents/olympic.png" },
  Alshahama: { name: "Alshahama", crest: "/opponents/alshahama.png" },
  "Al Jazira": {
    name: "Al Jazira",
    crest: "/opponents/al-jazira.png",
  },
  "Al Wahda": {
    name: "Al Wahda",
    crest: "/opponents/al-wahda.png",
  },
  "Arabian Falcons": {
    name: "Arabian Falcons",
    crest: "/opponents/arabian-falcons.png",
  },
};

export const phoenixLeagueFixtures = [
  {
    matchCode: 81921,
    week: 1,
    round: 1,
    date: "2026-09-04",
    time: "21:00",
    opponent: "PASS",
    location: "away",
    venue: "Sheikh Zayed Cricket Stadium / Sub 4",
    streamUrl: "https://smashi.tv/",
  },
  {
    matchCode: 81929,
    week: 2,
    round: 1,
    date: "2026-09-12",
    time: "20:00",
    opponent: "Arabian Falcons",
    location: "home",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 81937,
    week: 3,
    round: 1,
    date: "2026-09-20",
    time: "17:40",
    opponent: "Al Wahda",
    location: "away",
    venue: "Al Wahda Club / Academy Sub 1",
  },
  {
    matchCode: 81945,
    week: 4,
    round: 1,
    date: "2026-09-26",
    time: "20:00",
    opponent: "Al Jazira",
    location: "home",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 81960,
    week: 6,
    round: 1,
    date: "2026-10-10",
    time: "19:00",
    opponent: "Red Castle",
    location: "away",
    venue: "Zayed Sports City / Sub 1",
  },
  {
    matchCode: 81967,
    week: 7,
    round: 1,
    date: "2026-10-16",
    time: "20:00",
    opponent: "Stallions",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 81974,
    week: 8,
    round: 1,
    date: "2026-10-25",
    time: "20:00",
    opponent: "Stryx FC",
    location: "away",
    venue: "Citizens School / Main Pitch",
  },
  {
    matchCode: 81981,
    week: 9,
    round: 1,
    date: "2026-10-30",
    time: "20:00",
    opponent: "ISE",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 81988,
    week: 10,
    round: 1,
    date: "2026-11-07",
    time: "20:00",
    opponent: "Maracuja",
    location: "away",
    venue: "Al Rams Club / Saqr Sports Stadium",
  },
  {
    matchCode: 81995,
    week: 11,
    round: 1,
    date: "2026-11-21",
    time: "20:00",
    opponent: "Desert Falcon",
    location: "home",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 82009,
    week: 12,
    round: 1,
    date: "2026-11-28",
    time: "17:00",
    opponent: "IRISH",
    location: "away",
    venue: "JA Shooting Club / Pitch 3",
  },
  {
    matchCode: 82017,
    week: 13,
    round: 1,
    date: "2026-12-04",
    time: "20:00",
    opponent: "Circle Football",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82025,
    week: 14,
    round: 1,
    date: "2026-12-13",
    time: "17:45",
    opponent: "Al Fath FC",
    location: "away",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82033,
    week: 15,
    round: 1,
    date: "2026-12-18",
    time: "20:00",
    opponent: "Al Madinah Wanderers",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82041,
    week: 16,
    round: 1,
    date: "2026-12-26",
    time: "21:00",
    opponent: "Olympic",
    location: "away",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82049,
    week: 17,
    round: 1,
    date: "2027-01-02",
    time: "20:00",
    opponent: "Alshahama",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82057,
    week: 18,
    round: 2,
    date: "2027-02-05",
    time: "20:00",
    opponent: "PASS",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82065,
    week: 19,
    round: 2,
    date: "2027-02-14",
    time: "21:30",
    opponent: "Arabian Falcons",
    location: "away",
    venue: "JA Shooting Club / Pitch 2",
  },
  {
    matchCode: 82073,
    week: 20,
    round: 2,
    date: "2027-02-20",
    time: "21:30",
    opponent: "Al Wahda",
    location: "home",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 82081,
    week: 21,
    round: 2,
    date: "2027-02-28",
    time: "21:30",
    opponent: "Al Jazira",
    location: "away",
    venue: "Al Jazira Club / Academy Sub No.1",
  },
  {
    matchCode: 82096,
    week: 23,
    round: 2,
    date: "2027-03-12",
    time: "20:00",
    opponent: "Red Castle",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82103,
    week: 24,
    round: 2,
    date: "2027-03-20",
    time: "21:00",
    opponent: "Stallions",
    location: "away",
    venue: "Al Arabi Club / Sub No.1",
  },
  {
    matchCode: 82110,
    week: 25,
    round: 2,
    date: "2027-03-26",
    time: "20:00",
    opponent: "Stryx FC",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82117,
    week: 26,
    round: 2,
    date: "2027-04-02",
    time: "21:00",
    opponent: "ISE",
    location: "away",
    venue: "Ras Al Khaimah Club / Khalifa Bin Zayed Stadium",
  },
  {
    matchCode: 82124,
    week: 27,
    round: 2,
    date: "2027-04-09",
    time: "20:00",
    opponent: "Maracuja",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82131,
    week: 28,
    round: 2,
    date: "2027-04-16",
    time: "21:00",
    opponent: "Desert Falcon",
    location: "away",
    venue: "Dubai Sports City / Sub No.4",
  },
  {
    matchCode: 82145,
    week: 29,
    round: 2,
    date: "2027-04-24",
    time: "20:00",
    opponent: "IRISH",
    location: "home",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 82153,
    week: 30,
    round: 2,
    date: "2027-05-02",
    time: "20:00",
    opponent: "Circle Football",
    location: "away",
    venue: "Mleeha Club / MS No.1",
  },
  {
    matchCode: 82161,
    week: 31,
    round: 2,
    date: "2027-05-07",
    time: "20:00",
    opponent: "Al Fath FC",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82169,
    week: 32,
    round: 2,
    date: "2027-05-14",
    time: "20:00",
    opponent: "Al Madinah Wanderers",
    location: "away",
    venue: "Al Dhafra Club / MS No.2",
  },
  {
    matchCode: 82177,
    week: 33,
    round: 2,
    date: "2027-05-21",
    time: "20:00",
    opponent: "Olympic",
    location: "home",
    venue: "Mleeha Club / Sub No.1",
  },
  {
    matchCode: 82185,
    week: 34,
    round: 2,
    date: "2027-05-29",
    time: "20:30",
    opponent: "Alshahama",
    location: "away",
    venue: "Alshahama Club / Main Pitch",
  },
] as const satisfies readonly PhoenixFixture[];
