import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable("leads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  idempotencyKey: text("idempotency_key").notNull().unique(),
  leadType: text("lead_type").notNull(),
  applicantRole: text("applicant_role").notNull().default(""),
  guardianName: text("guardian_name").notNull().default(""),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  country: text("country").notNull(),
  dateOfBirth: text("date_of_birth").notNull().default(""),
  nationality: text("nationality").notNull().default(""),
  playerAge: integer("player_age"),
  preferredRoute: text("preferred_route").notNull().default(""),
  preferredHub: text("preferred_hub").notNull().default(""),
  accommodationPreference: text("accommodation_preference")
    .notNull()
    .default(""),
  position: text("position").notNull().default(""),
  currentClub: text("current_club").notNull().default(""),
  playingLevel: text("playing_level").notNull().default(""),
  highlightUrl: text("highlight_url").notNull().default(""),
  educationLevel: text("education_level").notNull().default(""),
  intendedStudy: text("intended_study").notNull().default(""),
  preferredIntake: text("preferred_intake").notNull().default(""),
  readinessTimeline: text("readiness_timeline").notNull().default(""),
  budgetReadiness: text("budget_readiness").notNull().default(""),
  familySupport: text("family_support").notNull().default(""),
  referralName: text("referral_name").notNull().default(""),
  collectionInterest: text("collection_interest").notNull().default(""),
  goal: text("goal").notNull().default(""),
  organization: text("organization").notNull().default(""),
  partnerInterest: text("partner_interest").notNull().default(""),
  message: text("message").notNull().default(""),
  contactPreference: text("contact_preference").notNull().default(""),
  consent: integer("consent", { mode: "boolean" }).notNull().default(false),
  sourceUrl: text("source_url").notNull().default(""),
  referrer: text("referrer").notNull().default(""),
  utmSource: text("utm_source").notNull().default(""),
  utmMedium: text("utm_medium").notNull().default(""),
  utmCampaign: text("utm_campaign").notNull().default(""),
  utmContent: text("utm_content").notNull().default(""),
  utmTerm: text("utm_term").notNull().default(""),
  gclid: text("gclid").notNull().default(""),
  fbclid: text("fbclid").notNull().default(""),
  language: text("language").notNull().default("en"),
  timezone: text("timezone").notNull().default(""),
  formVariant: text("form_variant").notNull().default(""),
  crmStatus: text("crm_status").notNull().default("queued"),
  crmResponse: text("crm_response").notNull().default(""),
  crmAttempts: integer("crm_attempts").notNull().default(0),
  crmLastAttemptAt: text("crm_last_attempt_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const leadRateLimits = sqliteTable("lead_rate_limits", {
  bucketKey: text("bucket_key").primaryKey(),
  count: integer("count").notNull().default(1),
  expiresAt: integer("expires_at").notNull(),
});
